// Generated by CoffeeScript 1.8.0

/*
  Тестовое приложение. Конфигурация приложения

  @author Vitaliy Kanev <1xamelion1@gmail.com>
  @see https://github.com/xamelion/example/tree/master/README.md>
  @license MIT https://github.com/xamelion/example/tree/master/LICENSE
 */

(function() {
  window.config = {
    siteLink: 'http://taxi.pios.cc/',
    useXDomain: false,
    debug: true,
    mainPage: '/',
    mainRouting: 'index.Main',
    template: 'test',
    debounce: 1000
  };

}).call(this);

//# sourceMappingURL=config.js.map
