// Generated by CoffeeScript 1.8.0

/*
  Подробности фотографии
  @author Vitaliy Kanev (1xamelion1@gmail.com)
  @version 0.0.0.1
 */

(function() {
  App.Controller.IndexView = {
    centerView: function($scope, $state, testService, testValue, api) {
      if (testValue.photos_id === false) {
        $state.go("index.Main");
        return false;
      }
      $scope.photos_id = testValue.photos_id;
      $scope.photos_public = testValue.photos_public;
      testService.title($scope.photos_public[$scope.photos_id].title);
      return $scope.item = function() {
        return $scope.photos_public[$scope.photos_id];
      };
    }
  };

}).call(this);

//# sourceMappingURL=index.view.js.map
