// Generated by CoffeeScript 1.8.0

/*
  Общая часть у дизайна index
  @author Vitaliy Kanev (1xamelion1@gmail.com)
  @version 0.0.0.1
 */

(function() {
  App.Controller.Index = {
    mainView: function($scope, testService, testValue) {
      return testService.title('Тестовое приложение');
    }
  };

}).call(this);

//# sourceMappingURL=index.js.map
